server:
  port: 8887

spring:
  application:
    name: web-front-service
  web:
    resources:
      static-locations: classpath:/static/

polar:
  auth-service-url: af92a482d3654425e86c3f7e570c9264-1319189162.ap-northeast-2.elb.amazonaws.com/auths
  catalog-service-url: af92a482d3654425e86c3f7e570c9264-1319189162.ap-northeast-2.elb.amazonaws.com/books
#  auth-service-url: ${AUTH_SERVICE_URL:http://localhost:9000}/auths
#  catalog-service-url: ${CATALOG_SERVICE_URL:http://localhost:9000}/books