server:
  port: 8887

spring:
  application:
    name: web-front-service
  web:
    resources:
      static-locations: classpath:/static/

polar:
  auth-service-url: a858ca36c9519456cab04d1804350151-1421811027.ap-northeast-2.elb.amazonaws.com/auths
  catalog-service-url: a858ca36c9519456cab04d1804350151-1421811027.ap-northeast-2.elb.amazonaws.com/books
#  auth-service-url: ${AUTH_SERVICE_URL:http://localhost:9000}/auths
#  catalog-service-url: ${CATALOG_SERVICE_URL:http://localhost:9000}/books