server:
  port: 9005

spring:
  application:
    name: web-front-service
  web:
    resources:
      static-locations: classpath:/static/

polar:
#  auth-service-url: a10111041f4ec411daa773d655def285-1442219654.ap-northeast-2.elb.amazonaws.com:80/auths
#  catalog-service-url: a10111041f4ec411daa773d655def285-1442219654.ap-northeast-2.elb.amazonaws.com:80/books
  edge-service-url: ${EDGE_SERVICE_URL:http://localhost:9000}
  auth-service-url: ${EDGE_SERVICE_URL:http://localhost:9000}/auths
  catalog-service-url: ${EDGE_SERVICE_URL:http://localhost:9000}/books