server:
  port: 8887

spring:
  application:
    name: web-front-service
  web:
    resources:
      static-locations: classpath:/static/

polar:
  auth-service-url: 172.20.231.191:80/auths
  catalog-service-url: 172.20.231.191:80/books
#  auth-service-url: ${AUTH_SERVICE_URL:http://localhost:9000}/auths
#  catalog-service-url: ${CATALOG_SERVICE_URL:http://localhost:9000}/books