server:
  port: 8887

spring:
  application:
    name: web-front-service
  web:
    resources:
      static-locations: classpath:/static/

polar:
  auth-service-uri: ${AUTH_SERVICE_URL:http://localhost:8886}